exports.Group = {
	//--------------------
	community: {
		communityID	 	: { $first: "$communityID"  },
		dbType		   	: { $first: "$dbType"       },
		dbID	   			: { $first: "$dbID"					},
		userID   			: { $first: "$userID"				},
		nickname     	: { $first: "$nickname"			},
		avatar      	: { $first: "$avatar"				},
		status    		: { $first: "$status"				},
		isVerified   	: { $first: "$isVerified"		},
		title	     		: { $first: "$title"				},
		excerpt	      : { $first: "$excerpt"			},
		content			 	: { $first: "$content"			},
		category		  : { $first: "$category"			},
		categories		: { $first: "$categories"		},
		tags		      : { $first: "$tags"					},
		featured     	: { $first: "$featured"			},
		images	      : { $first: "$images"				},
		created	      : { $first: "$created"			},
		updated	      : { $first: "$updated"			},
		deleted	      : { $first: "$deleted"			},
	},
	//--------------------
	comments: {
		commentID	   	: { $first: "$commentID" },
		dbType		   	: { $first: "$dbType" },
		dbID	   			: { $first: "$dbID" },
		userID   			: { $first: "$userID" },
		nickname     	: { $first: "$nickname" },
		avatar      	: { $first: "$avatar" },
		status    		: { $first: "$status" },
		isVerified   	: { $first: "$isVerified" },
		title	     		: { $first: "$title" },
		excerpt	      : { $first: "$excerpt" },
		content			 	: { $first: "$content" },
		categories		: { $first: "$categories" },
		tags		      : { $first: "$tags" },
		featured     	: { $first: "$featured" },
		images	      : { $first: "$images" },
		created	      : { $first: "$created" },
		updated	      : { $first: "$updated" },
		deleted	      : { $first: "$deleted" },
	},
	//--------------------
	replies: {
		replyID	   		: { $first: "$replyID" },
		commentID	   	: { $first: "$commentID" },
		dbType		   	: { $first: "$dbType" },
		dbID	   			: { $first: "$dbID" },
		userID   			: { $first: "$userID" },
		nickname     	: { $first: "$nickname" },
		avatar      	: { $first: "$avatar" },
		status    		: { $first: "$status" },
		isVerified   	: { $first: "$isVerified" },
		title	     		: { $first: "$title" },
		excerpt	      : { $first: "$excerpt" },
		content			 	: { $first: "$content" },
		categories		: { $first: "$categories" },
		tags		      : { $first: "$tags" },
		featured     	: { $first: "$featured" },
		images	      : { $first: "$images" },
		created	      : { $first: "$created" },
		updated	      : { $first: "$updated" },
	},
	//--------------------
	reactions: {
		likes     	: { $ifNull: [{ $sum: "$reactions.likes" 	  		}, 0] },
		dislikes  	: { $ifNull: [{ $sum: "$reactions.dislikes" 	  }, 0] },
		blinds    	: { $ifNull: [{ $sum: "$reactions.blinds" 	  	}, 0] },
		pins      	: { $ifNull: [{ $sum: "$reactions.pins" 	  		}, 0] },
		captures  	: { $ifNull: [{ $sum: "$reactions.captures" 	  }, 0] },
		shares    	: { $ifNull: [{ $sum: "$reactions.shares" 	  	}, 0] },
		views     	: { $ifNull: [{ $sum: "$reactions.views" 	  		}, 0] },
		follows   : { $ifNull: [{ $sum: "$reactions.follows" 	  }, 0] },
		followedBys	: { $ifNull: [{ $sum: "$reactions.followedBys"	}, 0] },
	
		pizzas    	: { $ifNull: [{ $avg: "$reactions.pizzas" 	  	}, 0] },
		ratings   	: { $ifNull: [{ $avg: "$reactions.commentID" 	  }, 0] },
	},
}