exports.Project = {
	//----------
	reactions: {
		communityID	: 1,
		dbType			: 1,
		dbID				: 1,
		userID			: 1,
		nickname		: 1,
		avatar			: 1,
		status			: 1,
		isVerified	: 1,
		title				: 1,
		excerpt			: 1,
		content			: 1,
		category    : 1,
		categories	: 1,
		tags				: 1,
		featured		: 1,
		images			: 1,
	},
	//----------
	comments: {
		_id         : 0,
		commentID		: 1,
		dbType			: 1,
		dbID				: 1,
		userID			: 1,
		nickname		: 1,
		avatar			: 1,
		status			: 1,
		isVerified	: 1,
		title				: 1,
		excerpt			: 1,
		content			: 1,
		categories	: 1,
		tags				: 1,
		featured		: 1,
		images			: 1,
		reactions   : 1,
		myReactions	: 1,
		replyCount	: { $size: "$replies" },
		replies			: 1,
	},
	//----------
	replies: {
		replyID: 1,
		commentID: 1,
		dbType: 1,
		dbID: 1,
		userID: 1,
		nickname: 1,
		avatar: 1,
		status: 1,
		isVerified: 1,
		title: 1,
		excerpt: 1,
		content: 1,
		categories: 1,
		tags: 1,
		featured: 1,
		images: 1,
		created: 1, updated: 1,
		reactions:"$_id",
		_id:0,
	},
	//----------
	community: {
		communityID	: 1,
		dbType			: 1,
		dbID				: 1,
		userID			: 1,
		nickname		: 1,
		avatar			: 1,
		status			: 1,
		isVerified	: 1,
		title				: 1,
		excerpt			: 1,
		content			: 1,
		category    : 1,
		categories	: 1,
		tags				: 1,
		featured		: 1,
		images			: 1,
	},
}