exports.nationalTable = [
	{ code: "AFG", name: "Afghanistan" },
	{ code: "AGU", name: "Anguilla" },
	{ code: "AHO", name: "Netherlands Antilles" },
	{ code: "AIN", name: "Individual Neutral Athlete" },
	{ code: "ALB", name: "Albania" },
	{ code: "ALG", name: "Algeria" },
	{ code: "AND", name: "Andorra" },
	{ code: "ANG", name: "Angola" },
	{ code: "ANT", name: "Antigua and Barbuda" },
	{ code: "ANZ", name: "Australasia" },
	{ code: "ARG", name: "Argentina" },
	{ code: "ARM", name: "Armenia" },
	{ code: "ART", name: "World Aquatics Refugee Team" },
	{ code: "ARU", name: "Aruba" },
	{ code: "ASA", name: "American Samoa" },
	{ code: "AUS", name: "Australia" },
	{ code: "AUT", name: "Austria" },
	{ code: "AZE", name: "Azerbaijan" },
	{ code: "BAH", name: "Bahamas" },
	{ code: "BAN", name: "Bangladesh" },
	{ code: "BAR", name: "Barbados" },
	{ code: "BDI", name: "Burundi" },
	{ code: "BEL", name: "Belgium" },
	{ code: "BEN", name: "Benin" },
	{ code: "BER", name: "Bermuda" },
	{ code: "BHU", name: "Bhutan" },
	{ code: "BIH", name: "Bosnia and Herzegovina" },
	{ code: "BIZ", name: "Belize" },
	{ code: "BLR", name: "Belarus" },
	{ code: "BOL", name: "Bolivia" },
	{ code: "BOT", name: "Botswana" },
	{ code: "BRA", name: "Brazil" },
	{ code: "BRN", name: "Bahrain" },
	{ code: "BRU", name: "Brunei Darussalam" },
	{ code: "BUL", name: "Bulgaria" },
	{ code: "BUR", name: "Burkina Faso" },
	{ code: "CAF", name: "Central African Republic" },
	{ code: "CAM", name: "Cambodia" },
	{ code: "CAN", name: "Canada" },
	{ code: "CAY", name: "Cayman Islands" },
	{ code: "CGO", name: "Republic of Congo" },
	{ code: "CHA", name: "Chad" },
	{ code: "CHI", name: "Chile" },
	{ code: "CHN", name: "People's Republic of China" },
	{ code: "CIS", name: "Commonwealth of Independent States" },
	{ code: "CIV", name: "Côte d'Ivoire" },
	{ code: "CMR", name: "Cameroon" },
	{ code: "COD", name: "Democratic Republic of the Congo" },
	{ code: "COK", name: "Cook Islands" },
	{ code: "COL", name: "Colombia" },
	{ code: "COM", name: "Comoros" },
	{ code: "CPV", name: "Cape Verde" },
	{ code: "CRC", name: "Costa Rica" },
	{ code: "CRO", name: "Croatia" },
	{ code: "CUB", name: "Cuba" },
	{ code: "CUR", name: "Curacao" },
	{ code: "CYP", name: "Cyprus" },
	{ code: "CZE", name: "Czechia" },
	{ code: "DEN", name: "Denmark" },
	{ code: "DJI", name: "Djibouti" },
	{ code: "DMA", name: "Dominica" },
	{ code: "DOM", name: "Dominican Republic" },
	{ code: "ECU", name: "Ecuador" },
	{ code: "EGY", name: "Egypt" },
	{ code: "EOR", name: "Refugee Olympic Team" },
	{ code: "ERI", name: "Eritrea" },
	{ code: "ESA", name: "El Salvador" },
	{ code: "ESP", name: "Spain" },
	{ code: "EST", name: "Estonia" },
	{ code: "ETH", name: "Ethiopia" },
	{ code: "EUA", name: "United Team of Germany" },
	{ code: "EUN", name: "Unified Team" },
	{ code: "FIJ", name: "Fiji" },
	{ code: "FIN", name: "Finland" },
	{ code: "FINA", name: "FINA" },
	{ code: "FRA", name: "France" },
	{ code: "FRG", name: "Federal Republic of Germany" },
	{ code: "FRO", name: "Faroe Islands" },
	{ code: "FSM", name: "Federated States of Micronesia" },
	{ code: "GAB", name: "Gabon" },
	{ code: "GAM", name: "Gambia" },
	{ code: "GBR", name: "Great Britain" },
	{ code: "GBS", name: "Guinea" },
	{ code: "GDR", name: "German Democratic Republic" },
	{ code: "GEO", name: "Georgia" },
	{ code: "GEQ", name: "Ecuatorial Guinea" },
	{ code: "GER", name: "Germany" },
	{ code: "GHA", name: "Ghana" },
	{ code: "GIB", name: "Gibraltar" },
	{ code: "GRE", name: "Greece" },
	{ code: "GRN", name: "Grenada" },
	{ code: "GUA", name: "Guatemala" },
	{ code: "GUI", name: "Guinea" },
	{ code: "GUM", name: "Guam" },
	{ code: "GUY", name: "Guyana" },
	{ code: "HAI", name: "Haiti" },
	{ code: "HKG", name: "Hong Kong, China" },
	{ code: "HON", name: "Honduras" },
	{ code: "HUN", name: "Hungary" },
	{ code: "INA", name: "Indonesia" },
	{ code: "IND", name: "India" },
	{ code: "IOA", name: "Individual Olympic Athletes" },
	{ code: "IOC", name: "International Olympic Committee" },
	{ code: "IOP", name: "Independent Olympic Participants" },
	{ code: "IRI", name: "Islamic Republic of Iran" },
	{ code: "IRL", name: "Ireland" },
	{ code: "IRQ", name: "Iraq" },
	{ code: "ISL", name: "Iceland" },
	{ code: "ISR", name: "Israel" },
	{ code: "ISV", name: "Virgin Islands, US" },
	{ code: "ITA", name: "Italy" },
	{ code: "IVB", name: "British Virgin Islands" },
	{ code: "JAM", name: "Jamaica" },
	{ code: "JOR", name: "Jordan" },
	{ code: "JPN", name: "Japan" },
	{ code: "KAZ", name: "Kazakhstan" },
	{ code: "KEN", name: "Kenya" },
	{ code: "KGZ", name: "Kyrgyzstan" },
	{ code: "KIR", name: "Kiribati" },
	{ code: "KOR", name: "Republic of Korea" },
	{ code: "KOS", name: "Kosovo" },
	{ code: "KSA", name: "Saudi Arabia" },
	{ code: "KUW", name: "Kuwait" },
	{ code: "LAO", name: "Lao People's Democratic Republic" },
	{ code: "LAT", name: "Latvia" },
	{ code: "LBA", name: "Libya" },
	{ code: "LBN", name: "Lebanon" },
	{ code: "LBR", name: "Liberia" },
	{ code: "LCA", name: "Saint Lucia" },
	{ code: "LES", name: "Lesotho" },
	{ code: "LIE", name: "Liechtenstein" },
	{ code: "LTU", name: "Lithuania" },
	{ code: "LUX", name: "Luxembourg" },
	{ code: "MAA", name: "Sint Maarten" },
	{ code: "MAC", name: "Macau, China" },
	{ code: "MAD", name: "Madagascar" },
	{ code: "MAR", name: "Morocco" },
	{ code: "MAS", name: "Malaysia" },
	{ code: "MAW", name: "Malawi" },
	{ code: "MDA", name: "Republic of Moldova" },
	{ code: "MDV", name: "Maldives" },
	{ code: "MEX", name: "Mexico" },
	{ code: "MGL", name: "Mongolia" },
	{ code: "MHL", name: "Marshall Islands" },
	{ code: "MKD", name: "North Macedonia" },
	{ code: "MLI", name: "Mali" },
	{ code: "MLT", name: "Malta" },
	{ code: "MNE", name: "Montenegro" },
	{ code: "MON", name: "Monaco" },
	{ code: "MOZ", name: "Mozambique" },
	{ code: "MRI", name: "Mauritius" },
	{ code: "MTN", name: "Mauritania" },
	{ code: "MYA", name: "Myanmar" },
	{ code: "NAA", name: "Neutral Athletes A" },
	{ code: "NAB", name: "Neutral Athletes B" },
	{ code: "NAC", name: "Neutral Athletes C" },
	{ code: "NAM", name: "Namibia" },
	{ code: "NCA", name: "Nicaragua" },
	{ code: "NED", name: "Netherlands" },
	{ code: "NEP", name: "Nepal" },
	{ code: "NGR", name: "Nigeria" },
	{ code: "NIA", name: "Neutral Independent Athletes" },
	{ code: "NIG", name: "Niger" },
	{ code: "NMA", name: "Northern Mariana Islands" },
	{ code: "NOR", name: "Norway" },
	{ code: "NRU", name: "Nauru" },
	{ code: "NZL", name: "New Zealand" },
	{ code: "OMA", name: "Oman" },
	{ code: "PAK", name: "Pakistan" },
	{ code: "PAN", name: "Panama" },
	{ code: "PAR", name: "Paraguay" },
	{ code: "PER", name: "Peru" },
	{ code: "PHI", name: "Philippines" },
	{ code: "PLE", name: "Palestine" },
	{ code: "PLW", name: "Palau" },
	{ code: "PNG", name: "Papua New Guinea" },
	{ code: "POL", name: "Poland" },
	{ code: "POR", name: "Portugal" },
	{ code: "PRK", name: "Democratic People's Republic of Korea" },
	{ code: "PUR", name: "Puerto Rico" },
	{ code: "QAT", name: "Qatar" },
	{ code: "RHO", name: "Rhodesia" },
	{ code: "ROC", name: "ROC" },
	{ code: "ROU", name: "Romania" },
	{ code: "RSA", name: "South Africa" },
	{ code: "RSF", name: "RSF" },
	{ code: "RUS", name: "Russian Federation" },
	{ code: "RWA", name: "Rwanda" },
	{ code: "SAA", name: "Saar" },
	{ code: "SAM", name: "Samoa" },
	{ code: "SCG", name: "Serbia and Montenegro" },
	{ code: "SEN", name: "Senegal" },
	{ code: "SEY", name: "Seychelles" },
	{ code: "SGP", name: "Singapore" },
	{ code: "SHN", name: "Saint Helena" },
	{ code: "SKN", name: "St. Kitts and Nevis" },
	{ code: "SLE", name: "Sierra Leone" },
	{ code: "SLO", name: "Slovenia" },
	{ code: "SMF", name: "Suspended Member Federation" },
	{ code: "SMR", name: "San Marino" },
	{ code: "SOL", name: "Solomon Islands" },
	{ code: "SOM", name: "Somalia" },
	{ code: "SRB", name: "Serbia" },
	{ code: "SRI", name: "Sri Lanka" },
	{ code: "STP", name: "São Tomé e Príncipe" },
	{ code: "SUD", name: "Sudan" },
	{ code: "SUI", name: "Switzerland" },
	{ code: "SUR", name: "Suriname" },
	{ code: "SVK", name: "Slovakia" },
	{ code: "SWE", name: "Sweden" },
	{ code: "SWZ", name: "Eswatini" },
	{ code: "SYR", name: "Syrian Arab Republic" },
	{ code: "TAH", name: "Tahiti" },
	{ code: "TAN", name: "United Republic of Tanzania" },
	{ code: "TCH", name: "Czechoslovakia" },
	{ code: "TCN", name: "Turks and Caicos Islands" },
	{ code: "TGA", name: "Tonga" },
	{ code: "THA", name: "Thailand" },
	{ code: "TJK", name: "Tajikistan" },
	{ code: "TKM", name: "Turkmenistan" },
	{ code: "TLS", name: "Democratic Republic of Timor" },
	{ code: "TOG", name: "Togo" },
	{ code: "TPE", name: "Chinese Taipei" },
	{ code: "TTO", name: "Trinidad and Tobago" },
	{ code: "TUN", name: "Tunisia" },
	{ code: "TUR", name: "Türkiye" },
	{ code: "TUV", name: "Tuvalu" },
	{ code: "UAE", name: "United Arab Emirates" },
	{ code: "UAR", name: "United Arab Republic" },
	{ code: "UGA", name: "Uganda" },
	{ code: "UKR", name: "Ukraine" },
	{ code: "URS", name: "Soviet Union" },
	{ code: "URU", name: "Uruguay" },
	{ code: "USA", name: "United States of America" },
	{ code: "UZB", name: "Uzbekistan" },
	{ code: "VAN", name: "Vanuatu" },
	{ code: "VEN", name: "Venezuela" },
	{ code: "VIE", name: "Vietnam" },
	{ code: "VIN", name: "Saint Vincent and the Grenadines" },
	{ code: "VNM", name: "South Vietnam" },
	{ code: "WIN", name: "West Indies" },
	{ code: "YEM", name: "Yemen" },
	{ code: "YUG", name: "Yugoslavia" },
	{ code: "ZAM", name: "Zambia" },
	{ code: "ZIM", name: "Zimbabwe" },
];
