exports.competitionTable = [
	{	cid: 77,	order: 105,	gubun: 'G',	gameNo: '105',	dateStart: '2024-10-11',	dateEnd: '2024-10-17',	place: '경상남도',	},
	{	cid: 76,	order: 104,	gubun: 'G',	gameNo: '104',	dateStart: '2023-10-13',	dateEnd: '2023-10-19',	place: '전라남도',	},
	{	cid: 75,	order: 103,	gubun: 'G',	gameNo: '103',	dateStart: '2022-10-07',	dateEnd: '2022-10-13',	place: '울산광역시',	},
	{	cid: 74,	order: 102,	gubun: 'G',	gameNo: '102',	dateStart: '2021-10-08',	dateEnd: '2021-10-14',	place: '경상북도',	},
	{	cid: 73,	order: 100,	gubun: 'G',	gameNo: '100',	dateStart: '2019-10-04',	dateEnd: '2019-10-10',	place: '서울특별시',	},
	{	cid: 72,	order: 99,	gubun: 'G',	gameNo: '99',	dateStart: '2018-10-12',	dateEnd: '2018-10-18',	place: '전라북도',	},
	{	cid: 71,	order: 98,	gubun: 'G',	gameNo: '98',	dateStart: '2017-10-20',	dateEnd: '2017-10-26',	place: '충청북도',	},
	{	cid: 70,	order: 97,	gubun: 'G',	gameNo: '97',	dateStart: '2016-10-07',	dateEnd: '2016-10-13',	place: '충청남도',	},
	{	cid: 69,	order: 96,	gubun: 'G',	gameNo: '96',	dateStart: '2015-10-16',	dateEnd: '2015-10-22',	place: '강원도',	},
	{	cid: 68,	order: 95,	gubun: 'G',	gameNo: '95',	dateStart: '2014-10-28',	dateEnd: '2014-11-03',	place: '제주특별자치도',	},
	{	cid: 67,	order: 94,	gubun: 'G',	gameNo: '94',	dateStart: '2013-10-18',	dateEnd: '2013-10-24',	place: '인천광역시',	},
	{	cid: 66,	order: 93,	gubun: 'G',	gameNo: '93',	dateStart: '2012-10-11',	dateEnd: '2012-10-17',	place: '대구광역시',	},
	{	cid: 65,	order: 92,	gubun: 'G',	gameNo: '92',	dateStart: '2011-10-06',	dateEnd: '2011-10-12',	place: '경기도',	},
	{	cid: 64,	order: 91,	gubun: 'G',	gameNo: '91',	dateStart: '2010-10-06',	dateEnd: '2010-10-12',	place: '경상남도',	},
	{	cid: 63,	order: 90,	gubun: 'G',	gameNo: '90',	dateStart: '2009-10-20',	dateEnd: '2009-10-26',	place: '대전광역시',	},
	{	cid: 62,	order: 89,	gubun: 'G',	gameNo: '89',	dateStart: '2008-10-10',	dateEnd: '2008-10-16',	place: '전라남도',	},
	{	cid: 61,	order: 88,	gubun: 'G',	gameNo: '88',	dateStart: '2007-10-08',	dateEnd: '2007-10-14',	place: '광주광역시',	},
	{	cid: 60,	order: 87,	gubun: 'G',	gameNo: '87',	dateStart: '2006-10-17',	dateEnd: '2006-10-23',	place: '경상북도',	},
	{	cid: 59,	order: 86,	gubun: 'G',	gameNo: '86',	dateStart: '2005-10-14',	dateEnd: '2005-10-20',	place: '울산광역시',	},
	{	cid: 58,	order: 85,	gubun: 'G',	gameNo: '85',	dateStart: '2004-10-08',	dateEnd: '2004-10-14',	place: '충청북도',	},
	{	cid: 57,	order: 84,	gubun: 'G',	gameNo: '84',	dateStart: '2003-10-10',	dateEnd: '2003-10-16',	place: '전라북도',	},
	{	cid: 56,	order: 83,	gubun: 'G',	gameNo: '83',	dateStart: '2002-11-09',	dateEnd: '2002-11-15',	place: '제주도',	},
	{	cid: 55,	order: 82,	gubun: 'G',	gameNo: '82',	dateStart: '2001-10-10',	dateEnd: '2001-10-16',	place: '충청남도',	},
	{	cid: 54,	order: 81,	gubun: 'G',	gameNo: '81',	dateStart: '2000-10-12',	dateEnd: '2000-10-18',	place: '부산광역시',	},
	{	cid: 53,	order: 80,	gubun: 'G',	gameNo: '80',	dateStart: '1999-10-11',	dateEnd: '1999-10-17',	place: '인천광역시',	},
	{	cid: 52,	order: 79,	gubun: 'G',	gameNo: '79',	dateStart: '1998-09-25',	dateEnd: '1998-10-01',	place: '제주도',	},
	{	cid: 51,	order: 78,	gubun: 'G',	gameNo: '78',	dateStart: '1997-10-08',	dateEnd: '1997-10-14',	place: '경상남도',	},
	{	cid: 50,	order: 77,	gubun: 'G',	gameNo: '77',	dateStart: '1996-10-07',	dateEnd: '1996-10-13',	place: '강원도',	},
	{	cid: 49,	order: 76,	gubun: 'G',	gameNo: '76',	dateStart: '1995-10-02',	dateEnd: '1995-10-08',	place: '경상북도',	},
	{	cid: 48,	order: 75,	gubun: 'G',	gameNo: '75',	dateStart: '1994-10-27',	dateEnd: '1994-11-02',	place: '대전직할시',	},
	{	cid: 47,	order: 74,	gubun: 'G',	gameNo: '74',	dateStart: '1993-10-11',	dateEnd: '1993-10-17',	place: '광주직할시',	},
	{	cid: 46,	order: 73,	gubun: 'G',	gameNo: '73',	dateStart: '1992-10-10',	dateEnd: '1992-10-16',	place: '대구',	},
	{	cid: 45,	order: 72,	gubun: 'G',	gameNo: '72',	dateStart: '1991-10-07',	dateEnd: '1991-10-13',	place: '전라북도',	},
	{	cid: 44,	order: 71,	gubun: 'G',	gameNo: '71',	dateStart: '1990-10-15',	dateEnd: '1990-10-21',	place: '충청북도',	},
	{	cid: 43,	order: 70,	gubun: 'G',	gameNo: '70',	dateStart: '1989-09-26',	dateEnd: '1989-10-01',	place: '경기도',	},
	{	cid: 42,	order: 68,	gubun: 'G',	gameNo: '68',	dateStart: '1987-10-13',	dateEnd: '1987-10-18',	place: '광주직할시',	},
	{	cid: 41,	order: 67,	gubun: 'G',	gameNo: '67',	dateStart: '1986-06-20',	dateEnd: '1986-06-25',	place: '서울, 경기, 부산',	},
	{	cid: 40,	order: 66,	gubun: 'G',	gameNo: '66',	dateStart: '1985-10-10',	dateEnd: '1985-10-15',	place: '강원도',	},
	{	cid: 39,	order: 65,	gubun: 'G',	gameNo: '65',	dateStart: '1984-10-11',	dateEnd: '1984-10-16',	place: '대구',	},
	{	cid: 38,	order: 64,	gubun: 'G',	gameNo: '64',	dateStart: '1983-10-06',	dateEnd: '1983-10-11',	place: '인천',	},
	{	cid: 37,	order: 63,	gubun: 'G',	gameNo: '63',	dateStart: '1982-10-14',	dateEnd: '1982-10-19',	place: '경상남도',	},
	{	cid: 36,	order: 62,	gubun: 'G',	gameNo: '62',	dateStart: '1981-10-10',	dateEnd: '1981-10-15',	place: '서울특별시',	},
	{	cid: 35,	order: 61,	gubun: 'G',	gameNo: '61',	dateStart: '1980-10-08',	dateEnd: '1980-10-13',	place: '전라북도',	},
	{	cid: 34,	order: 60,	gubun: 'G',	gameNo: '60',	dateStart: '1979-10-12',	dateEnd: '1979-10-17',	place: '충청남도',	},
	{	cid: 33,	order: 59,	gubun: 'G',	gameNo: '59',	dateStart: '1978-10-12',	dateEnd: '1978-10-17',	place: '경기(인천)',	},
	{	cid: 32,	order: 58,	gubun: 'G',	gameNo: '58',	dateStart: '1977-10-10',	dateEnd: '1977-10-15',	place: '전라남도(광주)',	},
	{	cid: 31,	order: 57,	gubun: 'G',	gameNo: '57',	dateStart: '1976-10-12',	dateEnd: '1976-10-17',	place: '부산',	},
	{	cid: 30,	order: 56,	gubun: 'G',	gameNo: '56',	dateStart: '1975-10-07',	dateEnd: '1975-10-12',	place: '경상북도(대구)',	},
	{	cid: 29,	order: 55,	gubun: 'G',	gameNo: '55',	dateStart: '1974-10-08',	dateEnd: '1974-10-13',	place: '서울',	},
	{	cid: 28,	order: 54,	gubun: 'G',	gameNo: '54',	dateStart: '1973-10-12',	dateEnd: '1973-10-17',	place: '부산',	},
	{	cid: 27,	order: 53,	gubun: 'G',	gameNo: '53',	dateStart: '1972-10-06',	dateEnd: '1972-10-11',	place: '서울특별시',	},
	{	cid: 26,	order: 52,	gubun: 'G',	gameNo: '52',	dateStart: '1971-10-08',	dateEnd: '1971-10-13',	place: '서울특별시',	},
	{	cid: 25,	order: 51,	gubun: 'G',	gameNo: '51',	dateStart: '1970-10-06',	dateEnd: '1970-10-11',	place: '서울특별시',	},
	{	cid: 24,	order: 50,	gubun: 'G',	gameNo: '50',	dateStart: '1969-10-28',	dateEnd: '1969-11-02',	place: '서울특별시',	},
	{	cid: 23,	order: 49,	gubun: 'G',	gameNo: '49',	dateStart: '1968-09-12',	dateEnd: '1968-09-17',	place: '서울특별시',	},
	{	cid: 22,	order: 48,	gubun: 'G',	gameNo: '48',	dateStart: '1967-10-05',	dateEnd: '1967-10-10',	place: '서울특별시',	},
	{	cid: 21,	order: 47,	gubun: 'G',	gameNo: '47',	dateStart: '1966-10-10',	dateEnd: '1966-10-15',	place: '서울특별시',	},
	{	cid: 20,	order: 46,	gubun: 'G',	gameNo: '46',	dateStart: '1965-10-05',	dateEnd: '1965-10-10',	place: '전라남도(광주)',	},
	{	cid: 19,	order: 45,	gubun: 'G',	gameNo: '45',	dateStart: '1964-09-03',	dateEnd: '1964-09-08',	place: '경기도',	},
	{	cid: 18,	order: 44,	gubun: 'G',	gameNo: '44',	dateStart: '1963-10-04',	dateEnd: '1963-10-09',	place: '전라북도(전주)',	},
	{	cid: 17,	order: 43,	gubun: 'G',	gameNo: '43',	dateStart: '1962-10-24',	dateEnd: '1962-10-29',	place: '경상북도(대구)',	},
	{	cid: 16,	order: 42,	gubun: 'G',	gameNo: '42',	dateStart: '1961-10-11',	dateEnd: '1961-10-15',	place: '서울특별시',	},
	{	cid: 15,	order: 41,	gubun: 'G',	gameNo: '41',	dateStart: '1960-10-10',	dateEnd: '1960-10-16',	place: '충청남도(대전)',	},
	{	cid: 14,	order: 40,	gubun: 'G',	gameNo: '40',	dateStart: '1959-10-03',	dateEnd: '1959-10-09',	place: '서울특별시',	},
	{	cid: 13,	order: 39,	gubun: 'G',	gameNo: '39',	dateStart: '1958-10-03',	dateEnd: '1958-10-09',	place: '서울특별시',	},
	{	cid: 12,	order: 38,	gubun: 'G',	gameNo: '38',	dateStart: '1957-10-18',	dateEnd: '1957-10-24',	place: '경상남도(부산)',	},
	{	cid: 11,	order: 37,	gubun: 'G',	gameNo: '37',	dateStart: '1956-10-03',	dateEnd: '1956-10-09',	place: '서울특별시',	},
	{	cid: 10,	order: 36,	gubun: 'G',	gameNo: '36',	dateStart: '1955-10-15',	dateEnd: '1955-10-22',	place: '서울특별시',	},
	{	cid: 9,	order: 35,	gubun: 'G',	gameNo: '35',	dateStart: '1954-10-19',	dateEnd: '1954-10-25',	place: '서울특별시',	},
	{	cid: 8,	order: 34,	gubun: 'G',	gameNo: '34',	dateStart: '1953-10-17',	dateEnd: '1953-10-22',	place: '서울특별시',	},
	{	cid: 7,	order: 33,	gubun: 'G',	gameNo: '33',	dateStart: '1952-10-18',	dateEnd: '1952-10-24',	place: '서울특별시',	},
	{	cid: 6,	order: 32,	gubun: 'G',	gameNo: '32',	dateStart: '1951-10-27',	dateEnd: '1951-10-31',	place: '전라남도(광주)',	},
	{	cid: 5,	order: 30,	gubun: 'G',	gameNo: '30',	dateStart: '1949-10-15',	dateEnd: '1949-10-23',	place: '서울특별시',	},
	{	cid: 4,	order: 29,	gubun: 'G',	gameNo: '29',	dateStart: '1948-10-20',	dateEnd: '1948-10-26',	place: '서울특별시',	},
	{	cid: 3,	order: 28,	gubun: 'G',	gameNo: '28',	dateStart: '1947-10-13',	dateEnd: '1947-10-19',	place: '서울특별시',	},
	// {	cid: 2,	order: 27,	gubun: 'G',	gameNo: '27',	dateStart: '1946-10-16',	dateEnd: '1946-10-20',	place: '서울특별시',	},
	// {	cid: 1,	order: 26,	gubun: 'G',	gameNo: '26',	dateStart: '1945-10-27',	dateEnd: '1945-10-30',	place: '서울특별시',	},
	{	cid: 126,	order: 54,	gubun: 'Y',	gameNo: '54',	dateStart: '2025-05-24',	dateEnd: '2025-05-27',	place: '경상남도',	},
	{	cid: 125,	order: 53,	gubun: 'Y',	gameNo: '53',	dateStart: '2024-05-25',	dateEnd: '2024-05-28',	place: '전라남도',	},
	{	cid: 124,	order: 52,	gubun: 'Y',	gameNo: '52',	dateStart: '2023-05-27',	dateEnd: '2023-05-30',	place: '울산광역시',	},
	{	cid: 123,	order: 51,	gubun: 'Y',	gameNo: '51',	dateStart: '2022-05-28',	dateEnd: '2022-05-31',	place: '경상북도',	},
	{	cid: 122,	order: 48,	gubun: 'Y',	gameNo: '48',	dateStart: '2019-05-25',	dateEnd: '2019-05-28',	place: '전라북도',	},
	{	cid: 121,	order: 47,	gubun: 'Y',	gameNo: '47',	dateStart: '2018-05-26',	dateEnd: '2018-05-29',	place: '충청북도',	},
	{	cid: 120,	order: 46,	gubun: 'Y',	gameNo: '46',	dateStart: '2017-05-27',	dateEnd: '2017-05-30',	place: '충청남도',	},
	{	cid: 119,	order: 45,	gubun: 'Y',	gameNo: '45',	dateStart: '2016-05-28',	dateEnd: '2016-05-31',	place: '강원도',	},
	{	cid: 118,	order: 44,	gubun: 'Y',	gameNo: '44',	dateStart: '2015-05-30',	dateEnd: '2015-06-02',	place: '제주특별자치도',	},
	{	cid: 117,	order: 43,	gubun: 'Y',	gameNo: '43',	dateStart: '2014-05-24',	dateEnd: '2014-05-27',	place: '인천광역시',	},
	{	cid: 116,	order: 42,	gubun: 'Y',	gameNo: '42',	dateStart: '2013-05-25',	dateEnd: '2013-05-28',	place: '대구광역시',	},
	{	cid: 115,	order: 41,	gubun: 'Y',	gameNo: '41',	dateStart: '2012-05-26',	dateEnd: '2012-05-29',	place: '경기도',	},
	{	cid: 114,	order: 40,	gubun: 'Y',	gameNo: '40',	dateStart: '2011-05-28',	dateEnd: '2011-05-31',	place: '경상남도',	},
	{	cid: 113,	order: 39,	gubun: 'Y',	gameNo: '39',	dateStart: '2010-08-11',	dateEnd: '2010-08-14',	place: '대전광역시',	},
	{	cid: 112,	order: 38,	gubun: 'Y',	gameNo: '38',	dateStart: '2009-05-30',	dateEnd: '2009-06-02',	place: '전라남도',	},
	{	cid: 111,	order: 37,	gubun: 'Y',	gameNo: '37',	dateStart: '2008-05-31',	dateEnd: '2008-06-03',	place: '광주광역시',	},
	{	cid: 110,	order: 36,	gubun: 'Y',	gameNo: '36',	dateStart: '2007-05-26',	dateEnd: '2007-05-29',	place: '경상북도',	},
	{	cid: 109,	order: 35,	gubun: 'Y',	gameNo: '35',	dateStart: '2006-06-17',	dateEnd: '2006-06-20',	place: '울산광역시',	},
	{	cid: 108,	order: 34,	gubun: 'Y',	gameNo: '34',	dateStart: '2005-05-27',	dateEnd: '2005-05-31',	place: '충청북도',	},
	{	cid: 107,	order: 33,	gubun: 'Y',	gameNo: '33',	dateStart: '2004-05-29',	dateEnd: '2004-06-01',	place: '전라북도',	},
	{	cid: 106,	order: 32,	gubun: 'Y',	gameNo: '32',	dateStart: '2003-05-31',	dateEnd: '2003-06-03',	place: '제주도',	},
	{	cid: 105,	order: 31,	gubun: 'Y',	gameNo: '31',	dateStart: '2002-05-11',	dateEnd: '2002-05-14',	place: '충청남도',	},
	{	cid: 104,	order: 30,	gubun: 'Y',	gameNo: '30',	dateStart: '2001-06-02',	dateEnd: '2001-06-05',	place: '부산광역시',	},
	{	cid: 103,	order: 29,	gubun: 'Y',	gameNo: '29',	dateStart: '2000-05-27',	dateEnd: '2000-05-30',	place: '인천',	},
	{	cid: 102,	order: 28,	gubun: 'Y',	gameNo: '28',	dateStart: '1999-05-29',	dateEnd: '1999-06-01',	place: '제주도',	},
	{	cid: 101,	order: 27,	gubun: 'Y',	gameNo: '27',	dateStart: '1998-05-23',	dateEnd: '1998-05-26',	place: '경상남도',	},
	{	cid: 100,	order: 26,	gubun: 'Y',	gameNo: '26',	dateStart: '1997-05-24',	dateEnd: '1997-05-27',	place: '강원도',	},
	{	cid: 99,	order: 25,	gubun: 'Y',	gameNo: '25',	dateStart: '1996-05-25',	dateEnd: '1996-05-28',	place: '경상북도',	},
	{	cid: 98,	order: 24,	gubun: 'Y',	gameNo: '24',	dateStart: '1995-05-27',	dateEnd: '1995-05-30',	place: '대전',	},
	{	cid: 97,	order: 23,	gubun: 'Y',	gameNo: '23',	dateStart: '1994-05-28',	dateEnd: '1994-05-31',	place: '광주',	},
	{	cid: 96,	order: 22,	gubun: 'Y',	gameNo: '22',	dateStart: '1993-05-28',	dateEnd: '1993-05-31',	place: '서울 경기',	},
	{	cid: 95,	order: 21,	gubun: 'Y',	gameNo: '21',	dateStart: '1992-06-13',	dateEnd: '1992-06-16',	place: '대구 광주외',	},
	{	cid: 94,	order: 17,	gubun: 'Y',	gameNo: '17',	dateStart: '1988-05-09',	dateEnd: '1988-05-22',	place: '전국 일원',	},
	{	cid: 93,	order: 16,	gubun: 'Y',	gameNo: '16',	dateStart: '1987-05-21',	dateEnd: '1987-05-25',	place: '부산,경남,포항,대',	},
	{	cid: 92,	order: 15,	gubun: 'Y',	gameNo: '15',	dateStart: '1986-05-05',	dateEnd: '1986-05-09',	place: '제주도외 전국분산',	},
	{	cid: 91,	order: 14,	gubun: 'Y',	gameNo: '14',	dateStart: '1985-05-22',	dateEnd: '1985-05-26',	place: '경상북도',	},
	{	cid: 90,	order: 13,	gubun: 'Y',	gameNo: '13',	dateStart: '1984-05-25',	dateEnd: '1984-05-29',	place: '제주도',	},
	{	cid: 89,	order: 12,	gubun: 'Y',	gameNo: '12',	dateStart: '1983-05-21',	dateEnd: '1983-05-25',	place: '전라북도',	},
	{	cid: 88,	order: 11,	gubun: 'Y',	gameNo: '11',	dateStart: '1982-05-19',	dateEnd: '1982-05-23',	place: '충청남도 대전시',	},
	{	cid: 87,	order: 10,	gubun: 'Y',	gameNo: '10',	dateStart: '1981-05-29',	dateEnd: '1981-06-01',	place: '전라남도',	},
	{	cid: 86,	order: 9,	gubun: 'Y',	gameNo: '9',	dateStart: '1980-06-10',	dateEnd: '1980-06-13',	place: '강원도',	},
	{	cid: 85,	order: 8,	gubun: 'Y',	gameNo: '8',	dateStart: '1979-05-30',	dateEnd: '1979-06-02',	place: '충청북도',	},
	{	cid: 84,	order: 7,	gubun: 'Y',	gameNo: '7',	dateStart: '1978-05-27',	dateEnd: '1978-05-30',	place: '경상북도 대구시',	},
	{	cid: 83,	order: 6,	gubun: 'Y',	gameNo: '6',	dateStart: '1977-06-01',	dateEnd: '1977-06-04',	place: '서울특별시',	},
	{	cid: 82,	order: 5,	gubun: 'Y',	gameNo: '5',	dateStart: '1976-06-03',	dateEnd: '1976-06-06',	place: '서울특별시',	},
	{	cid: 81,	order: 4,	gubun: 'Y',	gameNo: '4',	dateStart: '1975-05-31',	dateEnd: '1975-06-03',	place: '부산직할시',	},
	{	cid: 80,	order: 3,	gubun: 'Y',	gameNo: '3',	dateStart: '1974-06-04',	dateEnd: '1974-06-07',	place: '서울',	},
	{	cid: 79,	order: 2,	gubun: 'Y',	gameNo: '2',	dateStart: '1973-06-01',	dateEnd: '1973-06-04',	place: '대전',	},
	{	cid: 78,	order: 1,	gubun: 'Y',	gameNo: '1',	dateStart: '1972-06-16',	dateEnd: '1972-06-19',	place: '서울',	},
	{	cid: 128,	order: 25,	gubun: 'L',	gameNo: '25',	dateStart: '2025-04-24',	dateEnd: '2025-04-27',	place: '전라남도',	},
	{	cid: 127,	order: 24,	gubun: 'L',	gameNo: '24',	dateStart: '2024-04-25',	dateEnd: '2024-04-28',	place: '울산광역시',	},
];

exports.disciplineTable = [
	{	disciplineORG: "배영100M[4학년이하부]",	disciplineCustom: '배영 100M [4학년이하부]',	style: 'backstroke',	distance: '100M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "고등부배영100M",	disciplineCustom: '고등부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부배영100M",	disciplineCustom: '남고부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부배영 100M",	disciplineCustom: '남중부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부배영100M",	disciplineCustom: '남중부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학배영100M",	disciplineCustom: '수상대학 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "수상아동부배영100M",	disciplineCustom: '수상아동부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '수상아동부',	isAdult: false	},
	{	disciplineORG: "여고부배영100M",	disciplineCustom: '여고부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여국부배영100M",	disciplineCustom: '여국부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '여국부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 배영100M A",	disciplineCustom: '여중부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 배영100M B",	disciplineCustom: '여중부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부배영 100M",	disciplineCustom: '여중부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부배영100M",	disciplineCustom: '여중부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부배영 100M",	disciplineCustom: '중등부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "중등부배영100M",	disciplineCustom: '중등부 배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "배영 100M",	disciplineCustom: '배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "배영100",	disciplineCustom: '배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "배영100M",	disciplineCustom: '배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "배영100m",	disciplineCustom: '배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "배영　１００Ｍ",	disciplineCustom: '배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "배영１００Ｍ",	disciplineCustom: '배영 100M',	style: 'backstroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "고등부배영200M",	disciplineCustom: '고등부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부배영200M",	disciplineCustom: '남고부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부배영 200M",	disciplineCustom: '남중부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부배영200M",	disciplineCustom: '남중부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학배영200M",	disciplineCustom: '수상대학 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부배영200M",	disciplineCustom: '여고부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부배영 200M",	disciplineCustom: '여중부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부배영200M",	disciplineCustom: '여중부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부배영200M",	disciplineCustom: '중등부 배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "배영 200M",	disciplineCustom: '배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "배영200M",	disciplineCustom: '배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "배영200m",	disciplineCustom: '배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "배영　２００Ｍ",	disciplineCustom: '배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "배영２００Ｍ",	disciplineCustom: '배영 200M',	style: 'backstroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "배영 50m(1-2학년)",	disciplineCustom: '배영 50M (1-2학년)',	style: 'backstroke',	distance: '50M',	ageGroup: '1-2학년',	isAdult: false	},
	{	disciplineORG: "배영 50m(16~29세)",	disciplineCustom: '배영 50M (16~29세)',	style: 'backstroke',	distance: '50M',	ageGroup: '16~29세',	isAdult: true	},
	{	disciplineORG: "배영 50m(30~39세)",	disciplineCustom: '배영 50M (30~39세)',	style: 'backstroke',	distance: '50M',	ageGroup: '30~39세',	isAdult: true	},
	{	disciplineORG: "배영 50m(3-4학년)",	disciplineCustom: '배영 50M (3-4학년)',	style: 'backstroke',	distance: '50M',	ageGroup: '3-4학년',	isAdult: false	},
	{	disciplineORG: "배영 50m(40~49세)",	disciplineCustom: '배영 50M (40~49세)',	style: 'backstroke',	distance: '50M',	ageGroup: '40~49세',	isAdult: true	},
	{	disciplineORG: "(4학년이하부)배영50M",	disciplineCustom: '(4학년이하부) 배영 50M',	style: 'backstroke',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "배영50M(4학년이하부)",	disciplineCustom: '배영 50M (4학년이하부)',	style: 'backstroke',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "배영50M[4학년이하부]",	disciplineCustom: '배영 50M [4학년이하부]',	style: 'backstroke',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "배영 50m(50세 이상)",	disciplineCustom: '배영 50M (50세 이상)',	style: 'backstroke',	distance: '50M',	ageGroup: '50세 이상',	isAdult: true	},
	{	disciplineORG: "배영 50m(5-6학년)",	disciplineCustom: '배영 50M (5-6학년)',	style: 'backstroke',	distance: '50M',	ageGroup: '5-6학년',	isAdult: false	},
	{	disciplineORG: "아동배영50M",	disciplineCustom: '아동 배영 50M',	style: 'backstroke',	distance: '50M',	ageGroup: '아동',	isAdult: false	},
	{	disciplineORG: "저학년배영５０Ｍ",	disciplineCustom: '저학년 배영 50M',	style: 'backstroke',	distance: '50M',	ageGroup: '저학년',	isAdult: false	},
	{	disciplineORG: "배영 50m",	disciplineCustom: '배영 50M',	style: 'backstroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "배영50M",	disciplineCustom: '배영 50M',	style: 'backstroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "배영50m",	disciplineCustom: '배영 50M',	style: 'backstroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "배영５０Ｍ",	disciplineCustom: '배영 50M',	style: 'backstroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "평영100M[4학년이하부]",	disciplineCustom: '평영 100M [4학년이하부]',	style: 'breaststroke',	distance: '100M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "고등부평영100M",	disciplineCustom: '고등부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부평영100M",	disciplineCustom: '남고부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부평영 100M",	disciplineCustom: '남중부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부평영100M",	disciplineCustom: '남중부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학평영100M",	disciplineCustom: '수상대학 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "수상아동부평영100M",	disciplineCustom: '수상아동부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '수상아동부',	isAdult: false	},
	{	disciplineORG: "아동평영100M",	disciplineCustom: '아동 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '아동',	isAdult: false	},
	{	disciplineORG: "여고부평영100M",	disciplineCustom: '여고부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여고부평형100M",	disciplineCustom: '여고부 평형 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여국부평영100M",	disciplineCustom: '여국부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '여국부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여아동평영100M",	disciplineCustom: '여아동 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '여아동',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부평영 100M",	disciplineCustom: '여중부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부평영100M",	disciplineCustom: '여중부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부평영 100M",	disciplineCustom: '중등부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "중등부평영100M",	disciplineCustom: '중등부 평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "평영 100M",	disciplineCustom: '평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "평영100M",	disciplineCustom: '평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "평영100m",	disciplineCustom: '평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "평영　１００Ｍ",	disciplineCustom: '평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "평영１００Ｍ",	disciplineCustom: '평영 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "평형100M",	disciplineCustom: '평형 100M',	style: 'breaststroke',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "고등부평영200M",	disciplineCustom: '고등부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부평영200M",	disciplineCustom: '남고부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부평영 200M",	disciplineCustom: '남중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부평영200M",	disciplineCustom: '남중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부평영200M A",	disciplineCustom: '남중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부평영200M B",	disciplineCustom: '남중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학평영200M",	disciplineCustom: '수상대학 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부평영200M",	disciplineCustom: '여고부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여고부평형200M",	disciplineCustom: '여고부 평형 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여구부평영200M",	disciplineCustom: '여구부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '여구부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 평영200M A",	disciplineCustom: '여중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 평영200M B",	disciplineCustom: '여중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부평영 200M",	disciplineCustom: '여중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부평영200M",	disciplineCustom: '여중부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부평영200M",	disciplineCustom: '중등부 평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "평영 200M",	disciplineCustom: '평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평영200M",	disciplineCustom: '평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평영200M A",	disciplineCustom: '평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평영200M B",	disciplineCustom: '평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평영200m",	disciplineCustom: '평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평영　２００Ｍ",	disciplineCustom: '평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평영２００Ｍ",	disciplineCustom: '평영 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평형200M",	disciplineCustom: '평형 200M',	style: 'breaststroke',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "평영400M",	disciplineCustom: '평영 400M',	style: 'breaststroke',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "평영 50m(1-2학년)",	disciplineCustom: '평영 50M (1-2학년)',	style: 'breaststroke',	distance: '50M',	ageGroup: '1-2학년',	isAdult: false	},
	{	disciplineORG: "평영 50m(16~29세)",	disciplineCustom: '평영 50M (16~29세)',	style: 'breaststroke',	distance: '50M',	ageGroup: '16~29세',	isAdult: true	},
	{	disciplineORG: "평영 50m(30~39세)",	disciplineCustom: '평영 50M (30~39세)',	style: 'breaststroke',	distance: '50M',	ageGroup: '30~39세',	isAdult: true	},
	{	disciplineORG: "평영 50m(3-4학년)",	disciplineCustom: '평영 50M (3-4학년)',	style: 'breaststroke',	distance: '50M',	ageGroup: '3-4학년',	isAdult: false	},
	{	disciplineORG: "평영 50m(40~49세)",	disciplineCustom: '평영 50M (40~49세)',	style: 'breaststroke',	distance: '50M',	ageGroup: '40~49세',	isAdult: true	},
	{	disciplineORG: "(4학년이하부)평영50M",	disciplineCustom: '(4학년이하부) 평영 50M',	style: 'breaststroke',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "평영50M (4학년이하부)",	disciplineCustom: '평영 50M (4학년이하부)',	style: 'breaststroke',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "평영50M(4학년이하부)",	disciplineCustom: '평영 50M (4학년이하부)',	style: 'breaststroke',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "평영50M[4학년이하부]",	disciplineCustom: '평영 50M [4학년이하부]',	style: 'breaststroke',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "평영 50m(50세 이상)",	disciplineCustom: '평영 50M (50세 이상)',	style: 'breaststroke',	distance: '50M',	ageGroup: '50세 이상',	isAdult: true	},
	{	disciplineORG: "평영 50m(5-6학년)",	disciplineCustom: '평영 50M (5-6학년)',	style: 'breaststroke',	distance: '50M',	ageGroup: '5-6학년',	isAdult: false	},
	{	disciplineORG: "저학년평영　５０Ｍ",	disciplineCustom: '저학년 평영 50M',	style: 'breaststroke',	distance: '50M',	ageGroup: '저학년',	isAdult: false	},
	{	disciplineORG: "저학년평영５０Ｍ",	disciplineCustom: '저학년 평영 50M',	style: 'breaststroke',	distance: '50M',	ageGroup: '저학년',	isAdult: false	},
	{	disciplineORG: "평영 50m",	disciplineCustom: '평영 50M',	style: 'breaststroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "평영50M",	disciplineCustom: '평영 50M',	style: 'breaststroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "평영50m",	disciplineCustom: '평영 50M',	style: 'breaststroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "평영５０Ｍ",	disciplineCustom: '평영 50M',	style: 'breaststroke',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "접영100M[4학년이하부]",	disciplineCustom: '접영 100M [4학년이하부]',	style: 'butterfly',	distance: '100M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "고등부접영100M",	disciplineCustom: '고등부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부접영100M",	disciplineCustom: '남고부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부접영 100M",	disciplineCustom: '남중부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부접영100M",	disciplineCustom: '남중부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학접영100M",	disciplineCustom: '수상대학 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부접영100M",	disciplineCustom: '여고부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여국부접영100M",	disciplineCustom: '여국부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '여국부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부접영 100M",	disciplineCustom: '여중부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부접영100M",	disciplineCustom: '여중부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부접영100M",	disciplineCustom: '중등부 접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "버터푸라이100M",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "접영 100M",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "접영100M",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "접영100M A",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "접영100M B",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "접영100m",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "접영　１００Ｍ",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "접영１００Ｍ",	disciplineCustom: '접영 100M',	style: 'butterfly',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "고등부접영200M",	disciplineCustom: '고등부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부접영200M",	disciplineCustom: '남고부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부접영 200M",	disciplineCustom: '남중부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부접영200M",	disciplineCustom: '남중부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학접영200M",	disciplineCustom: '수상대학 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부접영200M",	disciplineCustom: '여고부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부접영 200M",	disciplineCustom: '여중부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부접영200M",	disciplineCustom: '여중부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부접영 200M",	disciplineCustom: '중등부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "중등부접영200M",	disciplineCustom: '중등부 접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "접영 200M",	disciplineCustom: '접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "접영200M",	disciplineCustom: '접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "접영200m",	disciplineCustom: '접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "접영　２００Ｍ",	disciplineCustom: '접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "접영２００Ｍ",	disciplineCustom: '접영 200M',	style: 'butterfly',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "접영 50m(1-2학년)",	disciplineCustom: '접영 50M (1-2학년)',	style: 'butterfly',	distance: '50M',	ageGroup: '1-2학년',	isAdult: false	},
	{	disciplineORG: "접영 50m(16~29세)",	disciplineCustom: '접영 50M (16~29세)',	style: 'butterfly',	distance: '50M',	ageGroup: '16~29세',	isAdult: true	},
	{	disciplineORG: "접영 50m(30~39세)",	disciplineCustom: '접영 50M (30~39세)',	style: 'butterfly',	distance: '50M',	ageGroup: '30~39세',	isAdult: true	},
	{	disciplineORG: "접영 50m(3-4학년)",	disciplineCustom: '접영 50M (3-4학년)',	style: 'butterfly',	distance: '50M',	ageGroup: '3-4학년',	isAdult: false	},
	{	disciplineORG: "접영 50m(40~49세)",	disciplineCustom: '접영 50M (40~49세)',	style: 'butterfly',	distance: '50M',	ageGroup: '40~49세',	isAdult: true	},
	{	disciplineORG: "(4학년이하부)접영50M",	disciplineCustom: '(4학년이하부) 접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "접영50M(4학년이하부)",	disciplineCustom: '접영 50M (4학년이하부)',	style: 'butterfly',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "접영50M[4학년이하부]",	disciplineCustom: '접영 50M [4학년이하부]',	style: 'butterfly',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "접영 50m(50세 이상)",	disciplineCustom: '접영 50M (50세 이상)',	style: 'butterfly',	distance: '50M',	ageGroup: '50세 이상',	isAdult: true	},
	{	disciplineORG: "접영 50m(5-6학년)",	disciplineCustom: '접영 50M (5-6학년)',	style: 'butterfly',	distance: '50M',	ageGroup: '5-6학년',	isAdult: false	},
	{	disciplineORG: "남중부 접영50M A",	disciplineCustom: '남중부 접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부 접영50M B",	disciplineCustom: '남중부 접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "저학년접영５０Ｍ",	disciplineCustom: '저학년 접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '저학년',	isAdult: false	},
	{	disciplineORG: "버터푸라이50M",	disciplineCustom: '접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "접영 50m",	disciplineCustom: '접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "접영50M",	disciplineCustom: '접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "접영50m",	disciplineCustom: '접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "접영５０Ｍ",	disciplineCustom: '접영 50M',	style: 'butterfly',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "남고부자유형1000M",	disciplineCustom: '남고부 자유형 1000M',	style: 'freestyle',	distance: '1000M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형1000M",	disciplineCustom: '남중부 자유형 1000M',	style: 'freestyle',	distance: '1000M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "자유형100M[4학년이하부]",	disciplineCustom: '자유형 100M [4학년이하부]',	style: 'freestyle',	distance: '100M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "고등부자유형100M",	disciplineCustom: '고등부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부자유형100M",	disciplineCustom: '남고부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형 100M",	disciplineCustom: '남중부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형100M",	disciplineCustom: '남중부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형100M A",	disciplineCustom: '남중부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형100M B",	disciplineCustom: '남중부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상자유형100M",	disciplineCustom: '수상 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '수상',	isAdult: true	},
	{	disciplineORG: "수상대학자유형100M",	disciplineCustom: '수상대학 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "수상아동부자유형100M",	disciplineCustom: '수상아동부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '수상아동부',	isAdult: false	},
	{	disciplineORG: "아동자유형100M",	disciplineCustom: '아동 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '아동',	isAdult: false	},
	{	disciplineORG: "여고부자유형100M",	disciplineCustom: '여고부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여국부자유형100M",	disciplineCustom: '여국부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '여국부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 자유형100M",	disciplineCustom: '여중부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부자유형 100M",	disciplineCustom: '여중부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부자유형100M",	disciplineCustom: '여중부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부자유형100M",	disciplineCustom: '중등부 자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "자유형 100M",	disciplineCustom: '자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "자유형100M",	disciplineCustom: '자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "자유형100m",	disciplineCustom: '자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "자유형　１００Ｍ",	disciplineCustom: '자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "자유형１００Ｍ",	disciplineCustom: '자유형 100M',	style: 'freestyle',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "고등부자유형1500M",	disciplineCustom: '고등부 자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부자유셩1500M",	disciplineCustom: '남고부 자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남고부자유형1500M",	disciplineCustom: '남고부 자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형1500M",	disciplineCustom: '남중부 자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상자유형1500M",	disciplineCustom: '수상 자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '수상',	isAdult: true	},
	{	disciplineORG: "수상대학자유형1500M",	disciplineCustom: '수상대학 자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "자유형1500m (시범종목)",	disciplineCustom: '자유형 1500M (시범종목)',	style: 'freestyle',	distance: '1500M',	ageGroup: '시범종목',	isAdult: true	},
	{	disciplineORG: "중등부자유형1500M",	disciplineCustom: '중등부 자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "자유형 1,500M",	disciplineCustom: '자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '',	},
	{	disciplineORG: "자유형1,500M",	disciplineCustom: '자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '',	},
	{	disciplineORG: "자유형1500",	disciplineCustom: '자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '',	},
	{	disciplineORG: "자유형1500M",	disciplineCustom: '자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '',	},
	{	disciplineORG: "자유형1500m",	disciplineCustom: '자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '',	},
	{	disciplineORG: "자유형　１５００Ｍ",	disciplineCustom: '자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '',	},
	{	disciplineORG: "자유형１５００Ｍ",	disciplineCustom: '자유형 1500M',	style: 'freestyle',	distance: '1500M',	ageGroup: '',	},
	{	disciplineORG: "고등부자유형200M",	disciplineCustom: '고등부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부자유셩200M",	disciplineCustom: '남고부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남고부자유형200M",	disciplineCustom: '남고부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형 200M",	disciplineCustom: '남중부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형200M",	disciplineCustom: '남중부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부주유형200M",	disciplineCustom: '남중부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상자유형200M",	disciplineCustom: '수상 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '수상',	isAdult: true	},
	{	disciplineORG: "수상대학자유형200M",	disciplineCustom: '수상대학 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부자유형200M",	disciplineCustom: '여고부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 자유형200M",	disciplineCustom: '여중부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부자유형 200M",	disciplineCustom: '여중부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부자유형200M",	disciplineCustom: '여중부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부주유형200M",	disciplineCustom: '여중부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부자유형200M",	disciplineCustom: '중등부 자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "자유형 200M",	disciplineCustom: '자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "자유형200M",	disciplineCustom: '자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "자유형200m",	disciplineCustom: '자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "자유형　２００Ｍ",	disciplineCustom: '자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "자유형２００Ｍ",	disciplineCustom: '자유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "주유형200M",	disciplineCustom: '주유형 200M',	style: 'freestyle',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "자유형300M",	disciplineCustom: '자유형 300M',	style: 'freestyle',	distance: '300M',	ageGroup: '',	},
	{	disciplineORG: "고등부자유형400M",	disciplineCustom: '고등부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부자유형400M",	disciplineCustom: '남고부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형 400M",	disciplineCustom: '남중부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형400M",	disciplineCustom: '남중부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형400M A",	disciplineCustom: '남중부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형400M B",	disciplineCustom: '남중부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상자유형400M",	disciplineCustom: '수상 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '수상',	isAdult: true	},
	{	disciplineORG: "수상대학자유형400M",	disciplineCustom: '수상대학 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부자유형400M",	disciplineCustom: '여고부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부자유형 400M",	disciplineCustom: '여중부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부자유형400M",	disciplineCustom: '여중부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부자유형400M",	disciplineCustom: '중등부 자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "자유형 400M",	disciplineCustom: '자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "자유형400M",	disciplineCustom: '자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "자유형400m",	disciplineCustom: '자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "자유형　４００Ｍ",	disciplineCustom: '자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "자유형４００Ｍ",	disciplineCustom: '자유형 400M',	style: 'freestyle',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "자유형 50m(1-2학년)",	disciplineCustom: '자유형 50M (1-2학년)',	style: 'freestyle',	distance: '50M',	ageGroup: '1-2학년',	isAdult: false	},
	{	disciplineORG: "자유형 50m(16~29세)",	disciplineCustom: '자유형 50M (16~29세)',	style: 'freestyle',	distance: '50M',	ageGroup: '16~29세',	isAdult: true	},
	{	disciplineORG: "자유형 50m(30~39세)",	disciplineCustom: '자유형 50M (30~39세)',	style: 'freestyle',	distance: '50M',	ageGroup: '30~39세',	isAdult: true	},
	{	disciplineORG: "자유형 50m(3-4학년)",	disciplineCustom: '자유형 50M (3-4학년)',	style: 'freestyle',	distance: '50M',	ageGroup: '3-4학년',	isAdult: false	},
	{	disciplineORG: "자유형 50m(40~49세)",	disciplineCustom: '자유형 50M (40~49세)',	style: 'freestyle',	distance: '50M',	ageGroup: '40~49세',	isAdult: true	},
	{	disciplineORG: "(4학년이하부)자유형50M",	disciplineCustom: '(4학년이하부) 자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "자유형50M(4학년이하부)",	disciplineCustom: '자유형 50M (4학년이하부)',	style: 'freestyle',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "자유형50M[4학년이하부]",	disciplineCustom: '자유형 50M [4학년이하부]',	style: 'freestyle',	distance: '50M',	ageGroup: '4학년이하부',	isAdult: false	},
	{	disciplineORG: "자유형 50m(50세 이상)",	disciplineCustom: '자유형 50M (50세 이상)',	style: 'freestyle',	distance: '50M',	ageGroup: '50세 이상',	isAdult: true	},
	{	disciplineORG: "자유형 50m(5-6학년)",	disciplineCustom: '자유형 50M (5-6학년)',	style: 'freestyle',	distance: '50M',	ageGroup: '5-6학년',	isAdult: false	},
	{	disciplineORG: "아동자유형50M",	disciplineCustom: '아동 자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '아동',	isAdult: false	},
	{	disciplineORG: "저학년자유형５０Ｍ",	disciplineCustom: '저학년 자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '저학년',	isAdult: false	},
	{	disciplineORG: "자유형 50m",	disciplineCustom: '자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "자유형50M",	disciplineCustom: '자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "자유형50m",	disciplineCustom: '자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "자유형　　５０Ｍ",	disciplineCustom: '자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "자유형５０Ｍ",	disciplineCustom: '자유형 50M',	style: 'freestyle',	distance: '50M',	ageGroup: '',	},
	{	disciplineORG: "남중부자유형 800M",	disciplineCustom: '남중부 자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부자유형800M",	disciplineCustom: '남중부 자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "자유형800m (시범종목)",	disciplineCustom: '자유형 800M (시범종목)',	style: 'freestyle',	distance: '800M',	ageGroup: '시범종목',	isAdult: true	},
	{	disciplineORG: "중등부자유형 800M",	disciplineCustom: '중등부 자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "중등부자유형800M",	disciplineCustom: '중등부 자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "자유형800M",	disciplineCustom: '자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "자유형800m",	disciplineCustom: '자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "자유형　８００Ｍ",	disciplineCustom: '자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "자유형８００Ｍ",	disciplineCustom: '자유형 800M',	style: 'freestyle',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "여중부계영100M",	disciplineCustom: '여중부 계영 100M',	style: 'freestyleRelay',	distance: '100M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "계영100M",	disciplineCustom: '계영 100M',	style: 'freestyleRelay',	distance: '100M',	ageGroup: '',	},
	{	disciplineORG: "남고부계영200M",	disciplineCustom: '남고부 계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부계영200M",	disciplineCustom: '남중부 계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "여고부계영200M",	disciplineCustom: '여고부 계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여국부계영200M",	disciplineCustom: '여국부 계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '여국부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 계영200M",	disciplineCustom: '여중부 계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부계영200M",	disciplineCustom: '여중부 계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부계영200M",	disciplineCustom: '중등부 계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "계영 200m",	disciplineCustom: '계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "계영200M",	disciplineCustom: '계영 200M',	style: 'freestyleRelay',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "여고부계영300M",	disciplineCustom: '여고부 계영 300M',	style: 'freestyleRelay',	distance: '300M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "고등부계영400 M",	disciplineCustom: '고등부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부계영400M",	disciplineCustom: '남고부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부계영 400M",	disciplineCustom: '남중부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부계영400M",	disciplineCustom: '남중부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학계영400M",	disciplineCustom: '수상대학 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부계영400M",	disciplineCustom: '여고부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 계영400M",	disciplineCustom: '여중부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부계영 400M",	disciplineCustom: '여중부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부계영400M",	disciplineCustom: '여중부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부계영400M",	disciplineCustom: '중등부 계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "계영 400M",	disciplineCustom: '계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "계영400M",	disciplineCustom: '계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "계영400m",	disciplineCustom: '계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "계영　４００Ｍ",	disciplineCustom: '계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "계영４００Ｍ",	disciplineCustom: '계영 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "계형400M",	disciplineCustom: '계형 400M',	style: 'freestyleRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "고등부계영800M",	disciplineCustom: '고등부 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부게영800M",	disciplineCustom: '남고부 게영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남고부계영800M",	disciplineCustom: '남고부 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부계영 800M",	disciplineCustom: '남중부 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부계영800M",	disciplineCustom: '남중부 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학계영800M",	disciplineCustom: '수상대학 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "여고부계영800M",	disciplineCustom: '여고부 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부계영800M",	disciplineCustom: '여중부 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부계영800M",	disciplineCustom: '중등부 계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "계영 800M",	disciplineCustom: '계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "계영800M",	disciplineCustom: '계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "계영800m",	disciplineCustom: '계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "계영　８００Ｍ",	disciplineCustom: '계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "계영８００Ｍ",	disciplineCustom: '계영 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "계형800M",	disciplineCustom: '계형 800M',	style: 'freestyleRelay',	distance: '800M',	ageGroup: '',	},
	{	disciplineORG: "고등부개인혼영200M",	disciplineCustom: '고등부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부개인혼영200M",	disciplineCustom: '남고부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부개인혼영 200",	disciplineCustom: '남중부 개인혼영 200',	style: 'individualMedley',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부개인혼영200",	disciplineCustom: '남중부 개인혼영200',	style: 'individualMedley',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부개인혼영200M",	disciplineCustom: '남중부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학개인혼영200M",	disciplineCustom: '수상대학 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "개인혼영200m (시범종목)",	disciplineCustom: '개인혼영 200M (시범종목)',	style: 'individualMedley',	distance: '200M',	ageGroup: '시범종목',	isAdult: true	},
	{	disciplineORG: "여고부개인혼영200M",	disciplineCustom: '여고부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여국부개인혼영200M",	disciplineCustom: '여국부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '여국부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부개인혼영 200M",	disciplineCustom: '여중부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부개인혼영200",	disciplineCustom: '여중부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부개인혼영200M",	disciplineCustom: '여중부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부개인혼영200M",	disciplineCustom: '중등부 개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "개인혼영 200M",	disciplineCustom: '개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영200M",	disciplineCustom: '개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영200m",	disciplineCustom: '개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영　２００Ｍ",	disciplineCustom: '개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영２００Ｍ",	disciplineCustom: '개인혼영 200M',	style: 'individualMedley',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "고등부개인혼영400M",	disciplineCustom: '고등부 개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부개인혼영400M",	disciplineCustom: '남고부 개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부개인혼영400M",	disciplineCustom: '남중부 개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "여고부개인혼영400M",	disciplineCustom: '여고부 개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부개인혼영400M",	disciplineCustom: '여중부 개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부개인혼영400M",	disciplineCustom: '중등부 개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "개인혼영 400M",	disciplineCustom: '개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영400",	disciplineCustom: '개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영400M",	disciplineCustom: '개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영400m",	disciplineCustom: '개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영　４００Ｍ",	disciplineCustom: '개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "개인혼영４００Ｍ",	disciplineCustom: '개인혼영 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "개인혼형400M",	disciplineCustom: '개인혼형 400M',	style: 'individualMedley',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "여국부혼계영200M",	disciplineCustom: '여국부 혼계영 200M',	style: 'medleyRelay',	distance: '200M',	ageGroup: '여국부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "혼계영 200m",	disciplineCustom: '혼계영 200M',	style: 'medleyRelay',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "혼계영200M",	disciplineCustom: '혼계영 200M',	style: 'medleyRelay',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "혼계영２００Ｍ",	disciplineCustom: '혼계영 200M',	style: 'medleyRelay',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "혼영200M",	disciplineCustom: '혼영 200M',	style: 'medleyRelay',	distance: '200M',	ageGroup: '',	},
	{	disciplineORG: "남중부혼계영300M",	disciplineCustom: '남중부 혼계영 300M',	style: 'medleyRelay',	distance: '300M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "여고부혼계영300M",	disciplineCustom: '여고부 혼계영 300M',	style: 'medleyRelay',	distance: '300M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부 혼계영300M",	disciplineCustom: '여중부 혼계영 300M',	style: 'medleyRelay',	distance: '300M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부혼계영300M",	disciplineCustom: '중등부 혼계영 300M',	style: 'medleyRelay',	distance: '300M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "혼계영300M",	disciplineCustom: '혼계영 300M',	style: 'medleyRelay',	distance: '300M',	ageGroup: '',	},
	{	disciplineORG: "혼영300M",	disciplineCustom: '혼영 300M',	style: 'medleyRelay',	distance: '300M',	ageGroup: '',	},
	{	disciplineORG: "고등부혼계영400M",	disciplineCustom: '고등부 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '고등부',	isAdult: false	},
	{	disciplineORG: "남고부혼계영400M",	disciplineCustom: '남고부 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '남고부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "남중부혼계영400M",	disciplineCustom: '남중부 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "수상대학혼계영400M",	disciplineCustom: '수상대학 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '수상대학',	isAdult: true	},
	{	disciplineORG: "혼성혼계영400m (시범종목)",	disciplineCustom: '혼성혼계영 400M (시범종목)',	style: 'medleyRelay',	distance: '400M',	ageGroup: '시범종목',	gender: 'mixed',	isAdult: true	},
	{	disciplineORG: "여고부개인혼계영400M",	disciplineCustom: '여고부 개인혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여고부혼계영400M",	disciplineCustom: '여고부 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부혼계영 400M",	disciplineCustom: '여중부 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여중부혼계영400M",	disciplineCustom: '여중부 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '여중부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "중등부혼계영400M",	disciplineCustom: '중등부 혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "중등부혼영400M",	disciplineCustom: '중등부 혼영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '중등부',	isAdult: false	},
	{	disciplineORG: "혼계영 400M",	disciplineCustom: '혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "혼계영400M",	disciplineCustom: '혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "혼계영400m",	disciplineCustom: '혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "혼계영　４００Ｍ",	disciplineCustom: '혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "혼계영４００Ｍ",	disciplineCustom: '혼계영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "혼계형400M",	disciplineCustom: '혼계형 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "혼영400M",	disciplineCustom: '혼영 400M',	style: 'medleyRelay',	distance: '400M',	ageGroup: '',	},
	{	disciplineORG: "남중부혼계영800M",	disciplineCustom: '남중부 혼계영 800M',	style: 'medleyRelay',	distance: '800M',	ageGroup: '남중부',	gender: 'men',	isAdult: false	},
	{	disciplineORG: "여고부혼계영800M",	disciplineCustom: '여고부 혼계영 800M',	style: 'medleyRelay',	distance: '800M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
	{	disciplineORG: "여고부혼영800M",	disciplineCustom: '여고부 혼영 800M',	style: 'medleyRelay',	distance: '800M',	ageGroup: '여고부',	gender: 'women',	isAdult: false	},
];

exports.ageGroupTable = [
	{	ageGroupORG: '남13이하',	ageGroup: '13이하',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남16이하',	ageGroup: '16이하',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남고',	ageGroup: '남고',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남고부',	ageGroup: '남고부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남국부',	ageGroup: '남국부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남자12세이하부',	ageGroup: '12세이하부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남자13세이하부',	ageGroup: '13세이하부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남자15세이하부',	ageGroup: '15세이하부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남자16세이하부',	ageGroup: '16세이하부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남자18세이하부',	ageGroup: '18세이하부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남자19세이하부',	ageGroup: '19세이하부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남중',	ageGroup: '남중',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남중고부',	ageGroup: '중고부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남중부',	ageGroup: '남중부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남초',	ageGroup: '남초',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남초부',	ageGroup: '남초부',	gender: 'men',	isAdult: false,	},
	{	ageGroupORG: '남대부',	ageGroup: '남대부',	gender: 'men',	isAdult: true,	},
	{	ageGroupORG: '남일',	ageGroup: '남일',	gender: 'men',	isAdult: true,	},
	{	ageGroupORG: '남일반',	ageGroup: '일반',	gender: 'men',	isAdult: true,	},
	{	ageGroupORG: '남자일반부',	ageGroup: '일반부',	gender: 'men',	isAdult: true,	},
	{	ageGroupORG: '고등부',	ageGroup: '고등부',	gender: 'mixed',	isAdult: false,	},
	{	ageGroupORG: '소년부녀부',	ageGroup: '소년부녀부',	gender: 'mixed',	isAdult: false,	},
	{	ageGroupORG: '중학부',	ageGroup: '중학부',	gender: 'mixed',	isAdult: false,	},
	{	ageGroupORG: '대학부',	ageGroup: '대학부',	gender: 'mixed',	isAdult: true,	},
	{	ageGroupORG: '일반부',	ageGroup: '일반부',	gender: 'mixed',	isAdult: true,	},
	{	ageGroupORG: '여13이하',	ageGroup: '13이하',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여16이하',	ageGroup: '16이하',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여고',	ageGroup: '여고',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여고부',	ageGroup: '여고부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여국부',	ageGroup: '여국부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여자12세이하부',	ageGroup: '12세이하부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여자13세이하부',	ageGroup: '13세이하부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여자15세이하부',	ageGroup: '15세이하부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여자16세이하부',	ageGroup: '16세이하부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여자18세이하부',	ageGroup: '18세이하부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여자19세이하부',	ageGroup: '19세이하부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여중',	ageGroup: '여중',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여중고부',	ageGroup: '여중고부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여중부',	ageGroup: '여중부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여초',	ageGroup: '여초',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여초부',	ageGroup: '여초부',	gender: 'women',	isAdult: false,	},
	{	ageGroupORG: '여대부',	ageGroup: '여대부',	gender: 'women',	isAdult: true,	},
	{	ageGroupORG: '여일',	ageGroup: '여일',	gender: 'women',	isAdult: true,	},
	{	ageGroupORG: '여일반',	ageGroup: '일반',	gender: 'women',	isAdult: true,	},
	{	ageGroupORG: '여자일반부',	ageGroup: '여자일반부',	gender: 'women',	isAdult: true,	},
];